@PROJECT_NAME@: MessageWidget Class Reference
MessageWidget Class Reference
#include <messagewidget.hpp>
Public Types
enum Type { Information , Warning , Error }
Public Member Functions
MessageWidget (const QString &text, Type type=Type::Information, QWidget *parent=nullptr, QFrame::Shape shape=QFrame::StyledPanel, QFrame::Shadow shadow=QFrame::Raised)
~MessageWidget () override
void setPallete ()
QString text () const
void setText (const QString &text)
Type messageType () const
void setMessageType (Type type)
void updateLayout ()
void createLayout ()
int bestContentHeight () const
bool isCloseButtonVisible () const
void setCloseButtonVisible (bool show)
void addAction (QAction *action)
void removeAction (QAction *action)
Protected Member Functions
QSize sizeHint () const override
QSize minimumSizeHint () const override
void paintEvent (QPaintEvent *event) override
Re-implement this function to paint this widget.
bool event (QEvent *event) override
Re-implement this function to change the active QPalette etc.
Private Member Functions
void setupWidgets ()
void setupConnections ()
Private Attributes
gsl::owner< QToolButton * > m_closeBtn
gsl::owner< QAction * > m_closeAction
gsl::owner< QGridLayout * > m_grid
gsl::owner< QLabel * > m_label
Type m_messageType
Detailed Description
Todo:
write docs
Definition at line 20 of file messagewidget.hpp.
Member Enumeration Documentation
Type
enum MessageWidget::Type
Enumerator
Information
Warning
Error
Definition at line 26 of file messagewidget.hpp.
                   {
                 Information,
                 Warning,
                 Error,
         };
Constructor & Destructor Documentation
MessageWidget()
MessageWidget::MessageWidget (const QString & text, Type type = Type::Information, QWidget * parent = nullptr, QFrame::Shape shape = QFrame::StyledPanel, QFrame::Shadow shadow = QFrame::Raised) explicit
Default constructor
Definition at line 17 of file messagewidget.cpp.
         : QFrame{ parent }
         , m_closeBtn{ new QToolButton{ this } }
         , m_closeAction{ new QAction{ this } }
         , m_grid{ new QGridLayout{ this } }
         , m_label{ new QLabel{ text, this } }
         , m_messageType{ type }
 {
         setFrameShape( shape );
         setFrameShadow( shadow );
         createLayout();
         setPallete();
         ensurePolished();
         setupWidgets();
         setupConnections();
         update();
 }
~MessageWidget()
MessageWidget::~MessageWidget () override default
Member Function Documentation
addAction()
void MessageWidget::addAction (QAction * action)
Definition at line 71 of file messagewidget.cpp.
 {
         QFrame::addAction( action );
         updateLayout();
 }
References updateLayout().
bestContentHeight()
int MessageWidget::bestContentHeight () const
Definition at line 128 of file messagewidget.cpp.
 {
         int height = heightForWidth( width() );
         if ( height == -1 ) { height = sizeHint().height(); }
         return height;
 }
createLayout()
void MessageWidget::createLayout ()
Definition at line 112 of file messagewidget.cpp.
 {
         m_grid->addWidget( m_label, 0, 0 );
         m_grid->addWidget( m_closeBtn, 0, 1 );
         this->setLayout( m_grid );
         layout()->setContentsMargins( layout()->contentsMargins() + borderSize );
         if ( isVisible() )    // Call to virtual method 'MessageWidget::sizeHint' during construction bypasses virtual dispatch
         {
                 setFixedHeight( MessageWidget::sizeHint().height() );
         }
         updateGeometry();
 }
event()
bool MessageWidget::event (QEvent * event) override protected
Re-implement this function to change the active QPalette etc.
Parameters
event is the event to be processed
Returns
true if the event was processed
Definition at line 199 of file messagewidget.cpp.
 {
         if ( event->type() == QEvent::Polish && !layout() ) { createLayout(); }
         else if ( event->type() == QEvent::Show )
         {
                 setFixedHeight( bestContentHeight() );
         }
         else if ( event->type() == QEvent::ParentChange )
         {
                 setPallete();
         }
         return QFrame::event( event );
 }
isCloseButtonVisible()
bool MessageWidget::isCloseButtonVisible () const
Definition at line 91 of file messagewidget.cpp.
 {
         return m_closeBtn->isVisible();
 }
messageType()
MessageWidget::Type MessageWidget::messageType () const
Definition at line 102 of file messagewidget.cpp.
 { return m_messageType; }
minimumSizeHint()
QSize MessageWidget::minimumSizeHint () const override protected
Definition at line 168 of file messagewidget.cpp.
 {
         ensurePolished();
         return QFrame::minimumSizeHint();
 }
paintEvent()
void MessageWidget::paintEvent (QPaintEvent * event) override protected
Re-implement this function to paint this widget.
Parameters
event is the event to be processed
Definition at line 174 of file messagewidget.cpp.
 {
         Q_UNUSED( event )
         QPainter painter{ this };
         constexpr float radius = 4 * 0.6;
         const QRect innerRect = rect().marginsRemoved( QMargins() + borderSize / 2 );
         const QColor    color = palette().color( QPalette::Window );
         constexpr float alpha = 0.2;
         const QColor    parentWindowColor =
                 ( parentWidget() ? parentWidget()->palette() : qApp->palette() )
                         .color( QPalette::Window );
         const int newRed = ( color.red() * alpha )
                            + ( parentWindowColor.red() * ( 1 - alpha ) );
         const int newGreen = ( color.green() * alpha )
                              + ( parentWindowColor.green() * ( 1 - alpha ) );
         const int newBlue = ( color.blue() * alpha )
                             + ( parentWindowColor.blue() * ( 1 - alpha ) );
         painter.setPen( QPen( color, borderSize ) );
         painter.setBrush( QColor( newRed, newGreen, newBlue ) );
         painter.setRenderHint( QPainter::Antialiasing );
         painter.drawRoundedRect( innerRect, radius, radius );
 }
removeAction()
void MessageWidget::removeAction (QAction * action)
Definition at line 77 of file messagewidget.cpp.
 {
         QFrame::removeAction( action );
         updateLayout();
 }
References updateLayout().
setCloseButtonVisible()
void MessageWidget::setCloseButtonVisible (bool show)
Definition at line 96 of file messagewidget.cpp.
 {
         m_closeBtn->setVisible( show );
         updateGeometry();
 }
setMessageType()
void MessageWidget::setMessageType (MessageWidget::Type type)
Definition at line 104 of file messagewidget.cpp.
 {
         m_messageType = type;
         setPallete();
 }
setPallete()
void MessageWidget::setPallete ()
Definition at line 41 of file messagewidget.cpp.
 {
         QColor bgBaseColor;
         switch ( m_messageType )
         {
                 case MessageWidget::Information:
                         bgBaseColor.setRgb( 61, 174, 233 );
                         break;
                 case MessageWidget::Warning:
                         bgBaseColor.setRgb( 246, 116, 0 );
                         break;
                 case MessageWidget::Error:
                         bgBaseColor.setRgb( 218, 68, 83 );
                         break;
                 default: break;
         }
         QPalette palette = this->palette();
         palette.setColor( QPalette::Window, bgBaseColor );
         const QColor parentTextColor =
                 ( this->parentWidget() ? this->parentWidget()->palette()
                                        : qApp->palette() )
                         .color( QPalette::WindowText );
         m_label->setPalette( palette );
         QFrame::setPalette( palette );
 }
setText()
void MessageWidget::setText (const QString & text)
Definition at line 85 of file messagewidget.cpp.
 {
         m_label->setText( text );
         updateGeometry();
 }
setupConnections()
void MessageWidget::setupConnections () private
Definition at line 151 of file messagewidget.cpp.
 {
         connect( m_closeAction, &QAction::triggered, this, &MessageWidget::hide, Qt::UniqueConnection );
         connect( qApp,
                  &QApplication::paletteChanged,
                  this,
                  &MessageWidget::setPallete,
                  Qt::UniqueConnection );
 }
setupWidgets()
void MessageWidget::setupWidgets () private
Definition at line 136 of file messagewidget.cpp.
 {
         m_label->setSizePolicy( QSizePolicy::Preferred, QSizePolicy::Fixed );
         m_label->setTextInteractionFlags( Qt::TextBrowserInteraction );
         m_closeAction->setText( tr( "&Close", "@action:button" ) );
         QStyleOptionFrame opt;
         opt.initFrom( this );
         m_closeAction->setIcon(
                 style()->standardIcon( QStyle::SP_DialogCloseButton, &opt, this ) );
         m_closeBtn->setAutoRaise( true );
         m_closeBtn->setDefaultAction( m_closeAction );
 }
sizeHint()
QSize MessageWidget::sizeHint () const override protected
Definition at line 162 of file messagewidget.cpp.
 {
         ensurePolished();
         return QFrame::sizeHint();
 }
text()
QString MessageWidget::text () const
Definition at line 83 of file messagewidget.cpp.
 { return m_label->text(); }
updateLayout()
void MessageWidget::updateLayout ()
Definition at line 110 of file messagewidget.cpp.
 { createLayout(); }
Referenced by addAction(), and removeAction().
Member Data Documentation
m_closeAction
gsl::owner<QAction*> MessageWidget::m_closeAction private
Definition at line 77 of file messagewidget.hpp.
m_closeBtn
gsl::owner<QToolButton*> MessageWidget::m_closeBtn private
Definition at line 76 of file messagewidget.hpp.
m_grid
gsl::owner<QGridLayout*> MessageWidget::m_grid private
Definition at line 78 of file messagewidget.hpp.
m_label
gsl::owner<QLabel*> MessageWidget::m_label private
Definition at line 79 of file messagewidget.hpp.
m_messageType
Type MessageWidget::m_messageType private
Definition at line 81 of file messagewidget.hpp.
The documentation for this class was generated from the following files:
/mnt/Volume_3/Gentoo/projects/Cplus/SymbolFinder/src/DriverWidgets/messagewidget.hpp
/mnt/Volume_3/Gentoo/projects/Cplus/SymbolFinder/src/DriverWidgets/messagewidget.cpp